- id: '1672201353243'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '24'
      update_entities:
      - update.home_assistant_core_update
      - update.adguard_home_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      - update.cloudflared_update
      mobile_app_device: e9e4e423ec942a0441f3c3405799cbcb
      mobile_app_device_2: 2ef1666371710eae548562d960d36089
      run_config_check: true
      only_after: 00:00:00
- id: '1672349680012'
  alias: Alexa-IFFT - Turn off PC
  description: ''
  trigger:
  - platform: webhook
    webhook_id: alexa-ifft-turn-off-pc-Qo0cs6z0nqSKDQ_2vVKqnLw0
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: CHRISTIAN-PC
  mode: single
- id: '1672353016030'
  alias: Turn off bedroom light after 5m
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.local_smart_light_1
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.local_smart_light_1
  mode: single
- id: '1672380948372'
  alias: Daily maintenance
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: hassio.backup_full
    data: {}
  - service: homeassistant.restart
    data: {}
  mode: single
- id: '1672522611577'
  alias: Tariff automation
  description: Tariff automation
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: time
    at: '17:00:00'
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '19:00:00'
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: '22:00:00'
        before: '17:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: offpeak
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    - conditions:
      - condition: time
        after: '17:00:00'
        before: '18:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: shoulder
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    - conditions:
      - condition: time
        after: '18:00:00'
        before: '21:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: peak
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    - conditions:
      - condition: time
        after: '21:00:00'
        before: '22:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: shoulder
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    default:
    - service: select.select_option
      data:
        option: offpeak
      target:
        entity_id:
        - select.monthly_energy
        - select.pc_energy_cost
  mode: single
- id: '1672690462412'
  alias: Renew SSL certificate
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ssl_auto_renewal
  condition: []
  action:
  - service: notify.mobile_app_m2010j19cg
    data:
      message: SSL certificate auto renew has started
  - service: hassio.addon_start
    data:
      addon: core_letsencrypt
    enabled: true
  - service: input_datetime.set_datetime
    data:
      datetime: "{% set change_days = '89' | int %} {{ strptime(states('input_datetime.ssl_auto_renewal'),
        '%Y-%m-%d %H:%M:%S')\n   + timedelta(days=change_days) }}"
    target:
      entity_id: input_datetime.ssl_auto_renewal
  mode: single
- id: '1672712190023'
  alias: Daily Christian-PC WoL
  description: Bussiness day WoL
  trigger:
  - platform: time
    at: 08:25:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.christian_pc_wol
  mode: single
- id: '1673233928666'
  alias: Turn off charging - Christian
  description: ''
  use_blueprint:
    path: vorion/turn-off-phone-charging-after-the-phone-is-charged.yaml
    input:
      switch: switch.local_smart_plug_3
      phone_battery: sensor.m2010j19cg_battery_level
- id: '1673391186244'
  alias: Turn off charging - Christian-TB
  description: ''
  use_blueprint:
    path: vorion/turn-off-phone-charging-after-the-phone-is-charged.yaml
    input:
      switch: switch.local_smart_plug_3
      phone_battery: sensor.christian_tab_battery_level
- id: '1673477422415'
  alias: Turn on office light
  description: Automatically turn on office light
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - device_tracker.christian_pc
    from: not_home
    to: home
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: device_tracker.christian_pc
      state: home
  action:
  - service: light.turn_on
    data: {}
    target:
      device_id: b7759a1d8c5860001f4243f62650f458
  mode: single
- id: '1673488875924'
  alias: Sleep time
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - if:
    - condition: time
      after: '23:00:00'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.sleep_time
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.sleep_time
  mode: single
- id: '1673492717992'
  alias: Determine best humidity
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /30
  condition: []
  action:
  - if:
    - condition: template
      value_template: "{{ states('sensor.temperature_sensor_humidity') | float >\n
        \  state_attr('weather.home', 'humidity') | float }}"
    then:
    - service: input_select.select_option
      data:
        option: Outside
      target:
        entity_id: input_select.best_humidity
    else:
    - service: input_select.select_option
      data:
        option: Inside
      target:
        entity_id: input_select.best_humidity
  mode: single
- id: '1673493242815'
  alias: Humidity Alert
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.best_humidity
  condition:
  - condition: time
    after: 09:00:00
    before: '19:00:00'
  action:
  - if:
    - condition: state
      entity_id: input_select.best_humidity
      state: Inside
    then:
    - service: notify.notify
      data:
        message: Humidity outside is higher, close your windows!
        title: Humidity Alert
    else:
    - service: notify.notify
      data:
        message: Humidity inside is higher, open your windows!
        title: Humidity Alert
  mode: single
- id: '1673494217272'
  alias: Advanced medication reminder
  description: ''
  use_blueprint:
    path: Aohzan/medication_reminder_android.yaml
    input:
      reminder_time: '10:00:00'
      notify_device: e9e4e423ec942a0441f3c3405799cbcb
      notification_title: Medication Reminder
      input_boolean: input_boolean.medication
