- id: '1672201353243'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '24'
      update_entities:
      - update.home_assistant_core_update
      - update.adguard_home_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      - update.cloudflared_update
      mobile_app_device: e9e4e423ec942a0441f3c3405799cbcb
      mobile_app_device_2: 2ef1666371710eae548562d960d36089
      run_config_check: true
      only_after: 09:00:00
- id: '1672349680012'
  alias: Alexa-IFFT - Turn off PC
  description: ''
  trigger:
  - platform: webhook
    webhook_id: alexa-ifft-turn-off-pc-Qo0cs6z0nqSKDQ_2vVKqnLw0
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: CHRISTIAN-PC
  mode: single
- id: '1672353016030'
  alias: Turn off bedroom light after 5m
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.local_smart_light_1
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.local_smart_light_1
  mode: single
- id: '1672380948372'
  alias: Daily maintenance
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: hassio.backup_full
    data: {}
  - service: homeassistant.restart
    data: {}
  mode: single
- id: '1672522611577'
  alias: Tariff automation
  description: Tariff automation
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: time
    at: '17:00:00'
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '19:00:00'
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: '22:00:00'
        before: '17:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: offpeak
        target:
          entity_id: select.monthly_energy
    - conditions:
      - condition: time
        after: '17:00:00'
        before: '18:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: shoulder
        target:
          entity_id: select.monthly_energy
    - conditions:
      - condition: time
        after: '18:00:00'
        before: '21:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: peak
        target:
          entity_id: select.monthly_energy
    - conditions:
      - condition: time
        after: '21:00:00'
        before: '22:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: shoulder
        target:
          entity_id: select.monthly_energy
    default:
    - service: select.select_option
      data:
        option: offpeak
      target:
        entity_id: select.monthly_energy
  mode: single
