- id: '1672522611577'
  alias: ENERGY - Tariff automation
  description: Tariff automation
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: time
    at: '17:00:00'
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '19:00:00'
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: '22:00:00'
        before: '17:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.tariff_type
        data:
          option: Off peak
    - conditions:
      - condition: time
        after: '17:00:00'
        before: '18:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.tariff_type
        data:
          option: Shoulder
    - conditions:
      - condition: time
        after: '18:00:00'
        before: '21:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.tariff_type
        data:
          option: Peak
    - conditions:
      - condition: time
        after: '21:00:00'
        before: '22:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.tariff_type
        data:
          option: Shoulder
    default:
    - service: input_select.select_option
      target:
        entity_id: input_select.tariff_type
      data:
        option: Off peak
  mode: single
- id: '1672712190023'
  alias: PC - Daily Christian-PC WoL
  description: Bussiness day WoL
  trigger:
  - platform: time
    at: 08:25:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.christian_pc_wol
    data: {}
  mode: single
- id: '1673477422415'
  alias: LIGHT - Turn on office light
  description: Automatically turn on office light
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - binary_sensor.christian_pc
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.cecilia_pc
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
      after_offset: '-15'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.christian_pc
        state: 'on'
      - condition: state
        entity_id: binary_sensor.cecilia_pc
        state: 'on'
    - condition: state
      entity_id: switch.adaptive_lighting_office
      state: 'on'
  action:
  - service: light.turn_on
    data: {}
    target:
      area_id: office
  mode: single
- id: '1673492717992'
  alias: WEATHER - Determine best humidity
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /2
  conditions:
  - condition: time
    after: 09:00:00
    before: '19:00:00'
  - condition: state
    entity_id: group.residents
    state: 'on'
  actions:
  - if:
    - condition: template
      value_template: "{{ states('sensor.house_humidity') | float >\n   state_attr('weather.home',
        'humidity') | float }}"
    then:
    - data:
        option: Outside
      target:
        entity_id: input_select.best_humidity
      action: input_select.select_option
    else:
    - data:
        option: Inside
      target:
        entity_id: input_select.best_humidity
      action: input_select.select_option
  mode: single
- id: '1673493242815'
  alias: WEATHER - Humidity Alert
  description: ''
  triggers:
  - entity_id:
    - input_select.best_humidity
    trigger: state
  conditions: []
  actions:
  - if:
    - condition: and
      conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: group.christian_home
          state: 'on'
        - condition: state
          entity_id: group.cecilia_home
          state: 'on'
      - condition: time
        after: 09:00:00
        before: '19:00:00'
      - condition: state
        entity_id: input_select.best_humidity
        state: Inside
    then:
    - data:
        title: Humidity Alert
        message: Close windows.
      action: notify.notify
    else:
    - if:
      - condition: and
        conditions:
        - condition: or
          conditions:
          - condition: state
            entity_id: group.christian_home
            state: 'on'
          - condition: state
            entity_id: group.cecilia_home
            state: 'on'
        - condition: time
          after: 09:00:00
          before: '19:00:00'
        - condition: state
          entity_id: input_select.best_humidity
          state: Outside
      then:
      - data:
          title: Humidity Alert
          message: Open windows.
        action: notify.notify
  mode: single
- id: '1673494217272'
  alias: Advanced medication reminder
  description: ''
  use_blueprint:
    path: Aohzan/medication_reminder_android.yaml
    input:
      reminder_time: '10:00:00'
      notify_device: 8a131ca4e20a3734b8ca80461f781e5f
      notification_title: Medication Reminder
      input_boolean: input_boolean.medication
- id: '1674182650722'
  alias: LIGHT - Turn off all lights when away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.residents
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - bedroom
      - living_room
      - office
      - kitchen
  - service: remote.turn_off
    data: {}
    target:
      entity_id:
      - remote.bedroom_tv
      - remote.living_room_tv
  mode: single
- id: '1674225267956'
  alias: LIGHT - Turn on living room light
  description: Automatically turn on living room light
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - remote.living_room_tv
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: switch.adaptive_lighting_living_room
      state: 'on'
    - condition: state
      entity_id: light.living_room_light
      state: 'off'
    - condition: state
      entity_id: remote.living_room_tv
      state: 'on'
  action:
  - service: light.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1674367256897'
  alias: MEDIA - Theater mode paused
  description: ''
  triggers:
  - entity_id:
    - media_player.living_room_tv
    for:
      hours: 0
      minutes: 0
      seconds: 3
    from: playing
    to: paused
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.theater_mode
      state: 'on'
    - condition: sun
      after: sunset
      before: sunrise
    - condition: state
      entity_id: switch.adaptive_lighting_living_room
      state: 'off'
  actions:
  - data: {}
    target:
      area_id: living_room
    action: light.turn_on
  mode: single
- id: '1674367315493'
  alias: MEDIA - Theater mode playing
  description: ''
  triggers:
  - entity_id:
    - media_player.living_room_tv
    to: playing
    from:
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.theater_mode
      state: 'on'
    - condition: sun
      after: sunset
      before: sunrise
    - condition: state
      entity_id: switch.adaptive_lighting_living_room
      state: 'off'
  actions:
  - data: {}
    target:
      area_id: living_room
    action: light.turn_off
  mode: single
- id: '1674368220338'
  alias: MEDIA - Toggle theater mode
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.theater_mode
    from: 'off'
    to: 'on'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.theater_mode
      state: 'on'
    then:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: switch.adaptive_lighting_living_room
    - service: automation.trigger
      data: {}
      target:
        entity_id: automation.media_theater_mode_playing
    else:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: switch.adaptive_lighting_living_room
  mode: single
- id: '1674779503847'
  alias: LIGHT - Turn off Office
  description: ''
  triggers:
  - entity_id:
    - group.computers
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: state
  conditions:
  - condition: state
    entity_id: switch.adaptive_lighting_office
    state: 'on'
  actions:
  - data:
      transition: 5
    target:
      area_id: office
    action: light.turn_off
  mode: single
- id: '1674924848329'
  alias: SWITCH - Toggle Office light
  description: ''
  use_blueprint:
    path: seamus65/ZHA - Sonoff SNZB-01.yaml
    input:
      remote: 5edfb7a20cc6bb8f565bac615b96acb1
      single_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.office_light
      double_press:
      - service: script.turn_on_off_christian_pc
        data: {}
- id: '1675913952899'
  alias: LIGHT - Turn on sleep time
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sleep_time
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.adaptive_lighting_sleep_mode_office
      - switch.adaptive_lighting_sleep_mode_living_room
      - switch.adaptive_lighting_sleep_mode_bedroom
  mode: single
- id: '1675914003290'
  alias: LIGHT - Turn off sleep time
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sleep_time
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.adaptive_lighting_sleep_mode_living_room
      - switch.adaptive_lighting_sleep_mode_office
      - switch.adaptive_lighting_sleep_mode_bedroom
  mode: single
- id: '1676734805757'
  alias: WASHER - Status Running
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_socket_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 1
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.washing_machine_status
  mode: single
- id: '1676744130645'
  alias: WASHER -  Finished
  description: ''
  triggers:
  - entity_id: sensor.washing_machine_socket_power
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 1
    trigger: numeric_state
  conditions:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'On'
  actions:
  - data:
      option: 'Off'
    target:
      entity_id: input_select.washing_machine_status
    action: input_select.select_option
  - data:
      message: Wash completed.
      title: Washing machine
    action: notify.notify
  mode: single
- id: '1680553973480'
  alias: SWITCH - Living room light
  description: ''
  use_blueprint:
    path: seamus65/ZHA - Sonoff SNZB-01.yaml
    input:
      remote: dce92ffa17e37194c258023c978b2cb9
      single_press:
      - service: light.toggle
        data: {}
        target:
          area_id: living_room
- id: '1680556356761'
  alias: SWITCH - Kitchen light
  description: ''
  use_blueprint:
    path: seamus65/ZHA - Sonoff SNZB-01.yaml
    input:
      remote: 32eb643cc51b1ff3098e619b102a920f
      single_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.kitchen_wall_switch_laundry_light
- id: '1684086727943'
  alias: ZONE - Cecilia arrived home
  description: ''
  use_blueprint:
    path: SirGoodenough/Person_Alert_Blueprint.yaml
    input:
      people2monitor:
      - person.cecilia_ueda
      zone2monitor:
      - zone.home
      hold_period:
        hours: 0
        minutes: 0
        seconds: 30
      leave_action: []
      enter_action:
      - service: notify.mobile_app_christian_sp
        data:
          title: Home assistant
          message: Cecilia has arrived home
- id: '1684184359544'
  alias: SWITCH - Turn off blanket after 3 hours
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.local_electric_blanket_socket
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: number.set_value
    data:
      value: '180'
    target:
      entity_id: number.local_electric_blanket_socket_timer
  mode: single
- id: '1697494475587'
  alias: Turn off server
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - bedroom
      - kitchen
      - living_room
      - office
    enabled: true
  - service: shell_command.server_shutdown
    data: {}
  mode: single
- id: '1700481253602'
  alias: JELLYFIN - Turn on
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.docker_start_jellyfin
    data: {}
  mode: single
- id: '1707155189687'
  alias: LIGHT - Turn off after HA starts
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id:
      - kitchen
      - living_room
      - office
      - bedroom
  mode: single
- id: '1712541558722'
  alias: SWITCH - Toggle bedroom lights
  description: ''
  use_blueprint:
    path: seamus65/ZHA - Sonoff SNZB-01.yaml
    input:
      remote: 18facb5be70163a5e4608f84f8df9613
      single_press:
      - metadata: {}
        data: {}
        target:
          entity_id: light.bedroom_lights
        action: light.toggle
      double_press:
      - metadata: {}
        data: {}
        action: light.toggle
        target:
          entity_id: light.closet_lightbulb
- id: '1726461621874'
  alias: SWITCH - Turn on CHRISTIAN-PC
  description: ''
  triggers:
  - at: 08:30:00
    trigger: time
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: calendar.feriados
    state: 'off'
  actions:
  - action: script.turn_on_off_christian_pc
    data: {}
  mode: single
- id: '1731122472243'
  alias: WEATHER - Change sunset offset
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.weather_clear_sky
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.weather_clear_sky
      state: 'off'
    then:
    - action: adaptive_lighting.change_switch_settings
      metadata: {}
      data:
        use_defaults: current
        entity_id: switch.adaptive_lighting_bedroom
        sunset_offset: -360
    - action: adaptive_lighting.change_switch_settings
      metadata: {}
      data:
        use_defaults: current
        entity_id: switch.adaptive_lighting_living_room
        sunset_offset: -360
    - action: adaptive_lighting.change_switch_settings
      metadata: {}
      data:
        use_defaults: current
        entity_id: switch.adaptive_lighting_office
        sunset_offset: -360
    else:
    - action: adaptive_lighting.change_switch_settings
      metadata: {}
      data:
        use_defaults: current
        entity_id: switch.adaptive_lighting_bedroom
        sunset_offset: 0
    - action: adaptive_lighting.change_switch_settings
      metadata: {}
      data:
        use_defaults: current
        entity_id: switch.adaptive_lighting_living_room
        sunset_offset: 0
    - action: adaptive_lighting.change_switch_settings
      metadata: {}
      data:
        use_defaults: current
        entity_id: switch.adaptive_lighting_office
        sunset_offset: 0
  mode: single
- id: '1732076375503'
  alias: FAN - Turn off after 4 hours
  description: ''
  triggers:
  - type: turned_on
    device_id: 208f96a94932b423396ca080292e6d7d
    entity_id: be8dd8aeff6add07dc6b91c62bf0ba5d
    domain: switch
    trigger: device
  conditions: []
  actions:
  - device_id: 208f96a94932b423396ca080292e6d7d
    domain: number
    entity_id: 8d0925ed90248965044f65cb5528eadb
    type: set_value
    value: 420
  mode: single
- id: '1747626186543'
  alias: SWITCH - Turn off TV
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
  conditions:
  - condition: device
    type: is_off
    device_id: 652cc01e99bf73414b83f1c055690f55
    entity_id: ccdf6818efa76df2585e16a6a79bc25a
    domain: light
  actions:
  - type: turn_off
    device_id: 027ef1e9569e2ed83b65c5645613b2f3
    entity_id: c846fdf5c8a2f0cceb365b0df0e4deca
    domain: switch
  mode: single
- id: '1747626567554'
  alias: SWITCH - Turn on TV
  description: ''
  triggers:
  - trigger: time
    at: 08:00:00
  conditions:
  - condition: device
    type: is_off
    device_id: 027ef1e9569e2ed83b65c5645613b2f3
    entity_id: c846fdf5c8a2f0cceb365b0df0e4deca
    domain: switch
  actions:
  - sequence:
    - type: turn_on
      device_id: 027ef1e9569e2ed83b65c5645613b2f3
      entity_id: c846fdf5c8a2f0cceb365b0df0e4deca
      domain: switch
    - delay:
        hours: 0
        minutes: 0
        seconds: 30
        milliseconds: 0
    - type: turn_on
      device_id: 19742bb5f634c575882bde80529497c1
      entity_id: db4802ea444f35f822f99976c5f05f17
      domain: remote
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - type: turn_off
      device_id: 19742bb5f634c575882bde80529497c1
      entity_id: db4802ea444f35f822f99976c5f05f17
      domain: remote
  mode: single
- id: '1749960944020'
  alias: OFFICE - Turn off thermostat
  description: ''
  triggers:
  - entity_id:
    - group.computers
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: state
  conditions: []
  actions:
  - action: climate.turn_off
    target:
      entity_id: climate.office_thermostat
    data: {}
  mode: single
