- id: '1672349680012'
  alias: Alexa-IFFT - Turn off PC
  description: ''
  trigger:
  - platform: webhook
    webhook_id: alexa-ifft-turn-off-pc-Qo0cs6z0nqSKDQ_2vVKqnLw0
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: CHRISTIAN-PC
  mode: single
- id: '1672353016030'
  alias: LIGHT - Turn off bedroom light after 5m
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.local_smart_light_1
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
    from: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.bedroom_light_automation
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.local_smart_light_1
  mode: single
- id: '1672522611577'
  alias: ENERGY - Tariff automation
  description: Tariff automation
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: time
    at: '17:00:00'
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '19:00:00'
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: '22:00:00'
        before: '17:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: offpeak
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    - conditions:
      - condition: time
        after: '17:00:00'
        before: '18:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: shoulder
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    - conditions:
      - condition: time
        after: '18:00:00'
        before: '21:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: peak
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    - conditions:
      - condition: time
        after: '21:00:00'
        before: '22:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: select.select_option
        data:
          option: shoulder
        target:
          entity_id:
          - select.monthly_energy
          - select.pc_energy_cost
    default:
    - service: select.select_option
      data:
        option: offpeak
      target:
        entity_id:
        - select.monthly_energy
        - select.pc_energy_cost
  mode: single
- id: '1672712190023'
  alias: PC - Daily Christian-PC WoL
  description: Bussiness day WoL
  trigger:
  - platform: time
    at: 08:25:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.christian_pc_wol
    data: {}
  mode: single
- id: '1673233928666'
  alias: PLUG - Turn off charging - Christian
  description: ''
  use_blueprint:
    path: vorion/turn-off-phone-charging-after-the-phone-is-charged.yaml
    input:
      switch: switch.local_smart_plug_3
      phone_battery: sensor.m2010j19cg_battery_level
- id: '1673391186244'
  alias: PLUG - Turn off charging - Christian-TB
  description: ''
  use_blueprint:
    path: vorion/turn-off-phone-charging-after-the-phone-is-charged.yaml
    input:
      switch: switch.local_smart_plug_3
      phone_battery: sensor.christian_tab_battery_level
- id: '1673477422415'
  alias: LIGHT - Turn on office light
  description: Automatically turn on office light
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - binary_sensor.christian_pc
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.cecilia_pc
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.christian_pc
        state: 'on'
      - condition: state
        entity_id: binary_sensor.cecilia_pc
        state: 'on'
    - condition: state
      entity_id: input_boolean.office_light_automation
      state: 'on'
  action:
  - service: light.turn_on
    data: {}
    target:
      area_id: office
  mode: single
- id: '1673492717992'
  alias: WEATHER - Determine best humidity
  description: ''
  trigger:
  - platform: time_pattern
    hours: /2
  condition: []
  action:
  - if:
    - condition: template
      value_template: "{{ states('sensor.temperature_sensor_humidity') | float >\n
        \  state_attr('weather.home', 'humidity') | float }}"
    then:
    - service: input_select.select_option
      data:
        option: Outside
      target:
        entity_id: input_select.best_humidity
    else:
    - service: input_select.select_option
      data:
        option: Inside
      target:
        entity_id: input_select.best_humidity
  mode: single
- id: '1673493242815'
  alias: WEATHER - Humidity Alert
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.best_humidity
  condition:
  - condition: time
    after: 09:00:00
    before: '19:00:00'
  action:
  - if:
    - condition: state
      entity_id: input_select.best_humidity
      state: Inside
    then:
    - service: notify.notify
      data:
        message: Humidity outside is higher, close your windows!
        title: Humidity Alert
    else:
    - service: notify.notify
      data:
        message: Humidity inside is higher, open your windows!
        title: Humidity Alert
  mode: single
- id: '1673494217272'
  alias: Advanced medication reminder
  description: ''
  use_blueprint:
    path: Aohzan/medication_reminder_android.yaml
    input:
      reminder_time: '10:00:00'
      notify_device: e9e4e423ec942a0441f3c3405799cbcb
      notification_title: Medication Reminder
      input_boolean: input_boolean.medication
- id: '1674136089586'
  alias: MEDIA - Turn off Living Room TV after 15 minutes
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.living_room_tv
    to: idle
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      device_id: 3626418d97b4e6150a57d17b9f5c03e7
  mode: single
- id: '1674182650722'
  alias: LIGHT - Turn off all lights when away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.residents
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - bedroom
      - living_room
      - office
  - service: switch.turn_off
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1674225267956'
  alias: LIGHT - Turn on living room light
  description: Automatically turn on living room light
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - media_player.living_room_tv
    to: playing
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: media_player.living_room_tv
      state: playing
    - condition: state
      entity_id: input_boolean.living_room_light_automation
      state: 'on'
  action:
  - service: light.turn_on
    data:
      transition: 3
    target:
      device_id: 93a0b1af02355fb7f993fe76e6f118f5
  mode: single
- id: '1674367256897'
  alias: MEDIA - Theater mode paused
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.living_room_tv
    to: paused
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.theater_mode
      state: 'on'
    - condition: sun
      after: sunset
      before: sunrise
    - condition: state
      entity_id: input_boolean.living_room_light_automation
      state: 'off'
  action:
  - service: light.turn_on
    data:
      transition: 10
    target:
      area_id: living_room
  mode: single
- id: '1674367315493'
  alias: MEDIA - Theater mode playing
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.living_room_tv
    to: playing
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.theater_mode
      state: 'on'
    - condition: sun
      after: sunset
      before: sunrise
    - condition: state
      entity_id: input_boolean.living_room_light_automation
      state: 'off'
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1674368220338'
  alias: MEDIA - Toggle theater mode
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.theater_mode
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.theater_mode
      state: 'on'
    then:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.living_room_light_automation
    - service: automation.trigger
      data: {}
      target:
        entity_id: automation.media_theater_mode_playing
    else:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.living_room_light_automation
  mode: single
- id: '1674779503847'
  alias: LIGHT - Turn off Office
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.computers
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: office
  mode: single
- id: '1674922819369'
  alias: SWITCH - Toggle Living room light
  description: ''
  use_blueprint:
    path: seamus65/ZHA - Sonoff SNZB-01.yaml
    input:
      remote: dce92ffa17e37194c258023c978b2cb9
      single_press:
      - service: light.toggle
        data:
          transition: 5
        target:
          area_id: living_room
      hold:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.theater_mode
- id: '1674924848329'
  alias: SWITCH - Toggle Office light
  description: ''
  use_blueprint:
    path: seamus65/ZHA - Sonoff SNZB-01.yaml
    input:
      remote: 5edfb7a20cc6bb8f565bac615b96acb1
      single_press:
      - service: light.toggle
        data:
          transition: 5
        target:
          area_id: office
      double_press:
      - service: script.turn_on_off_christian_pc
        data: {}
- id: '1674973427986'
  alias: LIGHT - Bedroom motion sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.zigbee_motion_sensor_iaszone
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_light_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_time
      state: 'off'
    - condition: sun
      before: sunrise
      after: sunset
  action:
  - service: light.turn_on
    entity_id: light.local_smart_light_1
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.zigbee_motion_sensor_iaszone
      from: 'on'
      to: 'off'
  - delay: 30
  - service: light.turn_off
    entity_id: light.local_smart_light_1
  mode: single
- id: '1675735214471'
  alias: LIGHT - Turn on bedroom on motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.zigbee_motion_sensor_iaszone
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_light_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_time
      state: 'off'
    - condition: sun
      after: sunset
      before: sunrise
  action:
  - service: light.turn_on
    data:
      transition: 5
    target:
      area_id: bedroom
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.zigbee_motion_sensor_iaszone
      to: 'off'
    continue_on_timeout: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: light.turn_off
    data:
      transition: 5
    target:
      area_id: bedroom
  mode: single
- id: '1675818897968'
  alias: Alexa-IFTTT - Start sleep time
  description: ''
  trigger:
  - platform: webhook
    webhook_id: alexa-ifttt-sleep-time-LP34aHLRNGZJnZOhSJiG4FAz
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sleep_time
  mode: single
- id: '1675902074913'
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action: []
  mode: single
- id: '1675913952899'
  alias: LIGHT - Turn on sleep time
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sleep_time
  mode: single
- id: '1675914003290'
  alias: LIGHT - Turn off sleep time
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sleep_time
  mode: single
