# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    zigpy.zcl: error
  filters:
    homeassistant.components.homeassistant_alerts:
      - "Timeout fetching homeassistant_alerts data"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: /hacsfiles/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

# Include folders
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
template: !include templates.yaml
group: !include groups.yaml
utility_meter: !include utility_meters.yaml
command_line: !include command_lines.yaml

# Folder whitelist
homeassistant:
  allowlist_external_dirs:
    - "/config/speedtest/"

# PowerCalc
powercalc:

# Conversation
conversation:

alexa:
  smart_home:
    locale: pt-BR
    filter:
      include_domains:
        - light
        - scene
        - script
      exclude_entities:
        - light.bedroom_lightbulb
        - light.kitchen_wall_switch_light_3
        - script.delete_orphaned_database_entities
        - script.vacuum_room_cleaning
      exclude_domains:
        - automation
        - binary_sensor
        - camera
        - device_tracker
        - lock
        - media_player
        - remote
        - sensor
        - switch
        - climate
        - input_button
        - group

# Cloud tunnel
http:
  use_x_forwarded_for: true
  trusted_proxies:
    #- 192.168.1.0/24
    - 172.21.0.0/16
    - 172.19.0.0/16
    - 127.0.0.1
    - ::1

# shell
shell_command:
  christian_pc_shutdown:  ssh -o 'StrictHostKeyChecking=no' hass@192.168.1.81 -i /config/ssh_keys/id_rsa_christian_pc "shutdown -s -t 30 -f"
  server_shutdown:        ssh -o 'StrictHostKeyChecking=no' christian@192.168.1.198 -i /config/ssh_keys/id_rsa_server "sudo shutdown -h now"
  christian_nb_shutdown:  ssh -o 'StrictHostKeyChecking=no' christian@192.168.1.118 -i /config/ssh_keys/id_rsa_christian_nb "shutdown -s -t 30 -f"
  docker_start_jellyfin:  ssh -o 'StrictHostKeyChecking=no' christian@192.168.1.198 -i /config/ssh_keys/id_rsa_server "docker start jellyfin"

# recorder
recorder:
  exclude:
    entities:
      - sensor.gpu_data
      - sensor.roborock_rooms