# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: /hacsfiles/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

# Include folders
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml

# PowerCalc
powercalc:

# Binary Sensor
binary_sensor:
  - platform: ping
    host: 204.2.229.94
    name: "FFXIV"
    count: 4
    scan_interval: 30
  - platform: ping
    host: 8.8.8.8
    name: "Google"
    count: 4
    scan_interval: 30
  - platform: ping
    host: 1.1.1.1
    name: "Cloudfare"
    count: 4
    scan_interval: 30

# Sensor
sensor:
  - platform: openhardwaremonitor
    host: 192.168.1.198
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use
      - type: memory_use_percent
  - platform: powercalc
    entity_id: light.ews_410
    linear:
      attribute: brightness
      min_power: 0.3
      max_power: 10
  - platform: powercalc
    entity_id: light.local_smart_light_1
    linear:
      attribute: brightness
      min_power: 0.3
      max_power: 10
  - platform: powercalc
    entity_id: light.local_smart_light_2
    linear:
      attribute: brightness
      min_power: 0.3
      max_power: 10
  - platform: powercalc
    entity_id: media_player.living_room_tv
    fixed:
      states_power:
        playing: 58.65
# Proximity
proximity:
  home_christian:
    zone: home
    devices:
      - device_tracker.m2010j19cg
    tolerance: 50
    unit_of_measurement: km
  home_cecilia:
    zone: home
    devices:
      - device_tracker.cecilia_sp
    tolerance: 50
    unit_of_measurement: km

# Cloudflare Tunnel
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Switch
switch:
  - platform: wake_on_lan
    mac: A8:A1:59:45:CB:22
    name: christian_pc_wol
    broadcast_address: 192.168.1.255
    turn_off:
      service: button.press
      data:
        addon: core_rpc_shutdown
        input: CHRISTIAN-PC

# Template
template:
  - sensor:
      - name: "Total Consumption"
        unit_of_measurement: "kWh"
        state: >
          {{
            [ states('sensor.local_smart_plug_1_consumption'),
              states('sensor.local_smart_plug_2_consumption'),
              states('sensor.local_smart_plug_3_consumption'),
              states('sensor.local_smart_light_1_energy'),
              states('sensor.local_smart_light_2_energy'),
              states('sensor.ews_410_energy'),
              states('sensor.living_room_tv_energy')]
              | map('float') | sum | round (2)
          }}
  - sensor:
      - name: "Tariff price"
        unit_of_measurement: BRL/kWh
        state: >
          {% if is_state('select.monthly_energy', 'peak') %}
              {{ 1.2839 }}
          {% elif is_state('select.monthly_energy', 'shoulder') %}
              {{ 0.86071 }}
          {% elif is_state('select.monthly_energy', 'offpeak') %}
              {{ 0.61755 }}
          {% endif %}
# Utility Meter
utility_meter:
  monthly_energy:
    source: sensor.total_consumption
    cycle: monthly
    tariffs:
      - peak
      - shoulder
      - offpeak
    offset:
      days: 20
      hours: 0
      minutes: 0
  pc_energy_cost:
    source: sensor.local_smart_plug_2_consumption
    cycle: monthly
    tariffs:
      - peak
      - shoulder
      - offpeak
    offset:
      days: 20
      hours: 0
      minutes: 0
