# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: /hacsfiles/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

# Include folders
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
template: !include templates.yaml
group: !include groups.yaml
utility_meter: !include utility_meters.yaml

# Folder whitelist
homeassistant:
  allowlist_external_dirs:
    - "/config/speedtest/"

# PowerCalc
powercalc:

# Proximity
proximity:
  home_christian:
    zone: home
    devices:
      - device_tracker.m2010j19cg
    tolerance: 50
    unit_of_measurement: km
  home_cecilia:
    zone: home
    devices:
      - device_tracker.cecilia_sp
    tolerance: 50
    unit_of_measurement: km

http:
  # ssl_certificate: /etc/letsencrypt/live/zaitsu.casa/fullchain.pem
  # ssl_key: /etc/letsencrypt/live/zaitsu.casa/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.21.0.0/24

# # Utility Meter
# utility_meter:
#   monthly_energy:
#     source: sensor.total_consumption
#     cycle: monthly
#     tariffs:
#       - peak
#       - shoulder
#       - offpeak
#     offset:
#       days: 20
#       hours: 0
#       minutes: 0
#   pc_energy_cost:
#     source: sensor.local_computer_socket_energy_helper
#     cycle: monthly
#     tariffs:
#       - peak
#       - shoulder
#       - offpeak
#     offset:
#       days: 20
#       hours: 0
#       minutes: 0

# Cicardian light
circadian_lighting:
  min_colortemp: 2004
  max_colortemp: 6535

shell_command:
  christian_pc_shutdown: ssh -o UserKnownHostsFile=/config/.ssh/known_hosts homeassistant@192.168.1.81 -i /config/.ssh/id_rsa "shutdown -s -t 30 -f"