- platform: history_stats
  name: Washer running time
  entity_id: input_select.washing_machine_status
  state: "On"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: rest
  name: roborock_rooms
  unique_id: 1f571dbe-7405-40d6-92e9-01d0ce4f4b8b
  resource: http://192.168.1.198:8123/local/Roborock/roborock.json
  value_template: "{{ now() }}"
  json_attributes:
    - rooms
    
- platform: openhardwaremonitor
  host: 192.168.1.116

# Powercalc
# - platform: powercalc
#   entity_id: binary_sensor.christian_srv
#   name: Server
#   fixed:
#     #HDD - 6.5W
#     #SSD - 0.6W
#     #2xRAM - 4W
#     #CPU Cooler - 5W (~2500RPM)
#     power: >-
#       {{ 
#         (
#           (states('sensor.christian_srv_intel_core_i7_3770k_powers_cpu_package') | float(0)) +
#           (states('sensor.christian_srv_nvidia_nvidia_geforce_gtx_1060_6gb_powers_gpu_power') | float(0)) +
#           6.5 + 0.6 + 4 + 5
#         ) | round(2) 
#       }}