# WOL
- platform: wake_on_lan
  mac: A8:A1:59:45:CB:22
  name: christian_pc_wol
  host: 192.168.1.81
  broadcast_address: 192.168.1.255
  turn_off:
    service: shell_command.christian_nb_shutdown

- platform: wake_on_lan
  mac: 80:FA:5B:A5:BA:D3
  name: christian_nb_wol
  host: 192.168.1.112
  broadcast_address: 192.168.1.255
  turn_off:
    service: shell_command.christian_nb_shutdown

- platform: wake_on_lan
  mac: 80:FA:5B:4A:21:7E
  name: hyper_v_server
  host: 192.168.1.116
  broadcast_address: 192.168.1.255

- platform: template
  switches:
    zigbee_kitchen_wall_switch_plug:
      unique_id: d463d2ce-ca24-4cce-901e-d1642aeeff4f
      friendly_name: "Kitchen wall switch plug"
      value_template: "{{ is_state('light.kitchen_wall_switch_light_3', 'on') }}"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.kitchen_wall_switch_light_3
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.kitchen_wall_switch_light_3